#include "gcode_export.h"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>

namespace dw {
namespace carve {

namespace {

// Format float with minimal trailing zeros (e.g., 5.0 not 5.000000)
std::string fmt(f32 v)
{
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%.3f", static_cast<double>(v));
    // Trim trailing zeros after decimal
    std::string s(buf);
    auto dot = s.find('.');
    if (dot != std::string::npos) {
        auto last = s.find_last_not_of('0');
        if (last == dot) {
            s.erase(dot + 2);  // Keep at least one decimal
        } else {
            s.erase(last + 1);
        }
    }
    return s;
}

void writeHeader(std::ostringstream& out,
                 const std::string& modelName,
                 const std::string& toolName,
                 const ToolpathConfig& config,
                 cnc::SendUnits units)
{
    out << "(Direct Carve - generated by Digital Workshop)\n";
    out << "(Model: " << modelName << ")\n";
    out << "(Tool: " << toolName << ")\n";
    out << "(Feed: " << fmt(cnc::toSendFeed(config.feedRateMmMin, units))
        << " " << cnc::feedUnitLabel(units)
        << ", Plunge: " << fmt(cnc::toSendFeed(config.plungeRateMmMin, units))
        << " " << cnc::feedUnitLabel(units) << ")\n";
    out << "(Safe Z: " << fmt(cnc::toSendLength(config.safeZMm, units))
        << " " << cnc::unitLabel(units) << ")\n";
}

void writePreamble(std::ostringstream& out, cnc::SendUnits units)
{
    out << "G90 " << cnc::gcodeUnitMode(units)
        << (units == cnc::SendUnits::Inches ? " (absolute, inch)\n"
                                            : " (absolute, metric)\n");
}

void writeToolpath(std::ostringstream& out,
                   const Toolpath& path,
                   const ToolpathConfig& config,
                   const std::string& passLabel,
                   f32& lastFeedRate,
                   bool& hasPosition,
                   Vec3& lastPosition,
                   bool& lastRapid,
                   cnc::SendUnits units)
{
    if (path.points.empty()) return;

    out << "(" << passLabel << " - " << path.lineCount << " lines, ~"
        << fmt(path.estimatedTimeSec / 60.0f) << " min)\n";

    for (const auto& pt : path.points) {
        if (pt.rapid) {
            out << "G0"
                << " X" << fmt(cnc::toSendLength(pt.position.x, units))
                << " Y" << fmt(cnc::toSendLength(pt.position.y, units))
                << " Z" << fmt(cnc::toSendLength(pt.position.z, units))
                << "\n";
            lastPosition = pt.position;
            lastRapid = true;
            hasPosition = true;
        } else {
            const f32 feedRate = hasPosition
                ? linearMoveFeedRateMmMin(lastPosition, lastRapid, pt.position, config)
                : config.feedRateMmMin;
            const f32 sendFeed = cnc::toSendFeed(feedRate, units);
            out << "G1"
                << " X" << fmt(cnc::toSendLength(pt.position.x, units))
                << " Y" << fmt(cnc::toSendLength(pt.position.y, units))
                << " Z" << fmt(cnc::toSendLength(pt.position.z, units));
            if (lastFeedRate < 0.0f || std::abs(sendFeed - lastFeedRate) > 0.001f) {
                out << " F" << fmt(sendFeed);
                lastFeedRate = sendFeed;
            }
            out << "\n";
            lastPosition = pt.position;
            lastRapid = false;
            hasPosition = true;
        }
    }
}

void writeToolChangeBoundary(std::ostringstream& out,
                             const MultiPassToolpath& toolpath,
                             const ToolpathConfig& config,
                             f32& lastFeedRate,
                             bool& hasPosition,
                             Vec3& lastPosition,
                             bool& lastRapid,
                             cnc::SendUnits units)
{
    const std::string roughTool = toolpath.clearingToolName.empty()
        ? "roughing tool"
        : toolpath.clearingToolName;
    const std::string finishTool = toolpath.finishingToolName.empty()
        ? "finish tool"
        : toolpath.finishingToolName;

    out << "(Tool change: " << roughTool << " -> "
        << finishTool << ")\n";
    out << "G0 Z" << fmt(cnc::toSendLength(config.safeZMm, units)) << "\n";
    out << "M5\n";
    out << "(Install finish tool: " << finishTool << ")\n";
    out << "(Re-zero Z with finish tool before continuing)\n";
    out << "M0\n";

    lastFeedRate = -1.0f;
    hasPosition = false;
    lastPosition = Vec3{0.0f};
    lastRapid = true;
}

void writeFooter(std::ostringstream& out, f32 safeZ, cnc::SendUnits units)
{
    out << "G0 Z" << fmt(cnc::toSendLength(safeZ, units)) << "\n";
    out << "M5\n";
    out << "M30\n";
}

} // anonymous namespace

std::string generateGcode(const MultiPassToolpath& toolpath,
                          const ToolpathConfig& config,
                          const std::string& modelName,
                          const std::string& toolName,
                          cnc::SendUnits units)
{
    std::ostringstream out;

    writeHeader(out, modelName, toolName, config, units);
    writePreamble(out, units);

    // Safe Z retract before starting
    out << "G0 Z" << fmt(cnc::toSendLength(config.safeZMm, units)) << "\n";

    f32 lastFeedRate = -1.0f;
    bool hasPosition = false;
    Vec3 lastPosition{0.0f};
    bool lastRapid = true;

    // Clearing pass first (if present)
    if (!toolpath.clearing.points.empty()) {
        writeToolpath(out, toolpath.clearing, config, "Clearing pass",
                      lastFeedRate, hasPosition, lastPosition, lastRapid, units);
    }

    if (toolpath.requiresToolChange &&
        !toolpath.clearing.points.empty() &&
        !toolpath.finishing.points.empty()) {
        writeToolChangeBoundary(out, toolpath, config,
                                lastFeedRate, hasPosition,
                                lastPosition, lastRapid, units);
    }

    // Finishing pass
    if (!toolpath.finishing.points.empty()) {
        writeToolpath(out, toolpath.finishing, config, "Finishing pass",
                      lastFeedRate, hasPosition, lastPosition, lastRapid, units);
    }

    writeFooter(out, config.safeZMm, units);

    return out.str();
}

bool exportGcode(const std::string& path,
                 const MultiPassToolpath& toolpath,
                 const ToolpathConfig& config,
                 const std::string& modelName,
                 const std::string& toolName,
                 cnc::SendUnits units)
{
    std::string gcode = generateGcode(toolpath, config, modelName, toolName, units);

    std::ofstream file(path, std::ios::out | std::ios::trunc);
    if (!file.is_open()) return false;

    file << gcode;
    return file.good();
}

} // namespace carve
} // namespace dw
